### ISSUE TITLE
Code uses libraries that were not explicitly required

### ISSUE THREAD

**Issue by abner-hb** [Novartis/bamdd#7]
In section [3 Model setup & priors](https://opensource.nibr.com/bamdd/src/01c_priors.html), the code uses functions from packages that are not explicitly required; not even in the ["R session setup"](https://opensource.nibr.com/bamdd/src/01b_basic_workflow.html#r-session-setup). For example, functions `stat_slab` from `ggdist`, `unnest_rvars` from `tidybayes`, and `fct_rev` from `forcats`. Could you add the names of all the libraries used at the beginning of each section?

**Comment by weberse2** [comment]
Thanks for reporting the matter. The intention of the first section of each case study is meant to load all required libraries - as you are expecting it. Let us look more closely into the one you quote and correct it accordingly.

**Comment by andrew-bean** [comment]
Looks like the code chunk that loads these packages at the top of the page in question was inadvertently hidden. PR incoming to make this visible (albeit in a collapsed code-fold block by default).
