### ISSUE TITLE
basic workflow page won't load 

### ISSUE THREAD

**Issue by statasaurus** [Novartis/bamdd#8]
I have tried on a couple different days but the basic workflow page won't load.

**Comment by luwidmer** [comment]
Hi! Odd, it loads fine for me:

![image](https://github.com/user-attachments/assets/3d693b07-0235-42d1-a44a-abf0df8f2fc1)

Is this always on the same machine and network, or did you try on a different machine / different network already?

**Comment by luwidmer** [comment]
@statasaurus: Could you try opening the page with developer tools active (F12 in most browsers) and see if anything hangs / errors in the Network pane? Since I can't reproduce the issue I don't even know where to start debugging.

**Comment by statasaurus** [comment]
This time it did load eventually, it did take a full minute. It does look like there is an issue in the network pane 
<img width="657" alt="image" src="https://github.com/user-attachments/assets/9a8a9b97-7205-410a-af1f-2496539d76a0">

**Comment by luwidmer** [comment]
Polyfill.io is probably the issue, see https://github.com/quarto-dev/quarto-cli/issues/10135 - looks like it timed out, on my machine it's blocked outright. Updating the quarto / pandoc versions should fix this, I think.

**Comment by andrew-bean** [comment]
This should be fixed by #11 because the site was re-rendered with the latest Quarto v1.5, which includes a fix. Please let us know if not @statasaurus (and thanks for reporting).

**Comment by statasaurus** [comment]
Sorry I checked and then didn't report back, yes it works now
